import { Metadata } from "next";
import { Contact } from "./Contact";

export const metadata: Metadata = {
  title: "Picture day | Contact-us",
  description: "Generated by picture day | Contact-us",
};

export default function Home() {
  return <Contact />;
}
