import { Metadata } from "next";
import { Print } from "./Prints";

export const metadata: Metadata = {
  title: "Picture day | Order Prints",
  description: "Generated by picture day | Order Prints",
};

export default function Home() {
  return <Print />;
}
