import { Metadata } from "next";
import { PictureDayForm } from "./PictureDayForm";

export const metadata: Metadata = {
  title: "Picture day | Book a photoshoot | Form",
  description: "Generated by picture day | Book a photoshoot | Form",
};

export default function Home() {
  return <PictureDayForm />;
}
