import { Metadata } from "next";
import { Photos } from "./Photos";

export const metadata: Metadata = {
  title: "Picture day | Photos",
  description: "Generated by picture day | Photos",
};

export default function Home() {
  return <Photos />;
}
